INSERT INTO items (id, title, description, points, category, icon, lat, lng, radius) VALUES
('item_stewart_rocket', 'By The Rocket', 'Grant was drafted in the military but was rejected because he had a squeaky knee and flat feet. He chose a job testing ammunition for the military. Take a picture by the rocket.', 30, 'Stewart Legacy', 'Parachute', NULL, NULL, NULL),
('item_stewart_magic_pot', 'Magic Soup Pot', 'Geneel made the best homemade soup with her magic soup pot. Find Marilyn and take a picture with the authentic magic pot.', 25, 'Stewart Legacy', 'Pot', NULL, NULL, NULL),
('item_stewart_basketball', 'Center Court', 'Grant was the center of his high school basketball team. Take a picture with the basketball courts in the background.', 25, 'Stewart Legacy', 'Basketball', NULL, NULL, NULL),
('item_stewart_root_beer', 'Root Beer Bench', 'Grant and Geneel loved to make homemade root beer for family occasions. Go to the bench by the tree and take your picture with the dads root beer bottle.', 25, 'Stewart Legacy', 'Glass', NULL, NULL, NULL),
('item_stewart_christmas', 'Christmas Sweatshirts', 'Geneel loved Christmas. She owned several Christmas sweatshirts and wore them proudly. Find Ileen and take a picture with the sweatshirts.', 20, 'Stewart Legacy', 'Gift', NULL, NULL, NULL),
('item_stewart_deer_hunt', 'Orange Hunter', 'Grant loved to deer hunt. Geneel disliked deer meat. Find a person wearing orange and take a picture with them.', 20, 'Stewart Legacy', 'Tree', NULL, NULL, NULL),
('item_stewart_popcorn', 'Bonanza Popcorn Toss', 'Every Sunday evening Grant and Geneel and their children would pop popcorn and watch Bonanza. Go to the northeast corner of the quad and take a picture with popcorn in the air.', 35, 'Stewart Legacy', 'Popcorn', NULL, NULL, NULL),
('item_stewart_three_bears', 'Three Bears Story', 'Geneel loved to read Goldilocks and the Three Bears to her grandchildren. Go to the three bears and take a picture.', 20, 'Stewart Legacy', 'Book', NULL, NULL, NULL),
('item_stewart_briefcase', 'Depot Briefcase', 'Grant worked at the Tooele Ordinance Depot and Tooele Army Depot in the Civil Service Personnel Department for over 30 years. Find the family briefcase he took to work and take a picture with it.', 30, 'Stewart Legacy', 'Briefcase', NULL, NULL, NULL),
('item_stewart_love_note', 'Fourth Grade Love Note', 'Geneel was a school teacher. She once received a love note from a fourth-grade student who said he wanted to marry her. Take a picture with the youngest in your group expressing love.', 25, 'Stewart Legacy', 'Heart', NULL, NULL, NULL),
('item_stewart_byu', 'BYU Letters', 'Grant graduated from BYU. Take a picture of your group using the letters B, Y, or U.', 20, 'Stewart Legacy', 'Flag', NULL, NULL, NULL),
('item_stewart_bear_lake', 'Bear Lake Condos', 'In 1979 Grant and Geneel purchased two Bear Lake condos. Take a picture with the words Bear Lake.', 20, 'Stewart Legacy', 'Sign', NULL, NULL, NULL),
('item_stewart_japan', 'Japan Dinner Table', 'Grant and Geneel took their family to Japan for two years. Find the sibling born there, get chopsticks, sit at a table, and take a photo pretending to eat dinner.', 35, 'Stewart Legacy', 'Globe', NULL, NULL, NULL),
('item_stewart_playground', 'Ideal Beach Playground', 'Grant and Geneel loved watching their posterity play on Ideal Beach playground equipment. Take a picture at the playground.', 20, 'Stewart Legacy', 'Playground', NULL, NULL, NULL),
('item_stewart_shells', 'Five Shells', 'Geneel loved collecting sea shells whenever she went on vacation. Find five shells and take a picture of your group with the shells.', 25, 'Stewart Legacy', 'Water', NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;
